import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SideNav from "./_components/common/SideNav";
import TopNav from "./_components/common/TopNav";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "A2SV Contest Central",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
