'use client'

// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Box, useMediaQuery } from '@mui/material'
import Header from './_components/Header'
import Drawer from './_components/Drawer'
import { useEffect, useState } from 'react'
import { useTheme } from '@mui/material/styles';
import ThemeCustomization from './themes'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const theme = useTheme();
  const matchDownLG = useMediaQuery(theme.breakpoints.down('lg'));

  const [open, setOpen] = useState(true);
  const handleDrawerToggle = () => {
    setOpen(!open);
  };

  // set media wise responsive drawer
  useEffect(() => {
    setOpen(!matchDownLG);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [matchDownLG]);

  return (
    <ThemeCustomization>
      <html lang="en">
        <body className={inter.className}>
          <Box sx={{ width: '100%' }}>
            <Header open={open} handleDrawerToggle={handleDrawerToggle} />
            <Drawer open={open} handleDrawerToggle={handleDrawerToggle} />
            <div className='pt-16 md:pl-64 md:pr-6 bg-primaryGray-100 w-full'>
              {children}
            </div>
          </Box>
        </body>
      </html>
    </ThemeCustomization>
  )
}
